server:
  port: 8001

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083/
          predicates:
            - Path=/**
        - id: first-service
          uri: http://localhost:8085/
          predicates:
                - Path=/first-service/**
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/**